#!/usr/bin/env python3
"""Generate a YouCompleteMe configuration file tailored to the host OS."""

import platform
from pathlib import Path
import textwrap

WORKSPACE = Path(__file__).resolve().parents[1]
TARGET = WORKSPACE / ".ycm_extra_conf.py"

COMMON_FLAGS = [
    "-Wall",
    "-Wextra",
    "-std=gnu11",
    "-mmcu=attiny85",
    "-DF_CPU=8000000UL",
    "-x",
    "c",
]

CONFIGS = {
    "Darwin": [
        "/opt/homebrew/Cellar/avr-gcc@9/9.5.0/avr/include",
        "/opt/homebrew/Cellar/avr-gcc@9/9.5.0/lib/avr-gcc/9/gcc/avr/9.5.0/include",
        "/opt/homebrew/Cellar/avr-gcc@9/9.5.0/lib/avr-gcc/9/gcc/avr/9.5.0/include-fixed",
    ],
    "Linux": [
        "/usr/lib/avr/include",
        "/usr/lib/gcc/avr/11/include",
        "/usr/lib/gcc/avr/9/include",
        "/usr/include",
    ],
}


def make_flags(include_paths: list[str]) -> list[str]:
    flags = []
    for idx, path in enumerate(include_paths):
        comment = "  # Path to avr/io.h for this configuration" if idx == 0 else ""
        flags.append((f"-I{path}", comment))
    flags.extend((flag, "") for flag in COMMON_FLAGS)
    return flags


def main() -> None:
    system = platform.system()
    include_paths = CONFIGS.get(system)
    if include_paths is None:
        raise SystemExit(f"Unsupported OS for YCM config: {system}")

    flags = make_flags(include_paths)
    unindented = "\n".join(
        f"{flag!r},{comment}" if comment else f"{flag!r},"
        for flag, comment in flags
    )
    flag_lines = textwrap.indent(unindented, """                """)
    content = textwrap.dedent(
        f"""\
        # Auto-generated by scripts/gen_ycm_conf.py for {system}
        def GetCompilationInfoForFile(filename):
            return {{
                'flags': [
{flag_lines}
                ],
                'do_cache': True,
            }}
        """
    )
    TARGET.write_text(content)
    print(f"Wrote {TARGET} for {system}")


if __name__ == "__main__":
    main()
